/*
export const CONFIG = {
  apiUrlLogin: 'http://172.16.51.102:5000/Login',
  apiFlujoCaja: 'http://172.16.51.102:5000/flujocaja',
  apiTipoServicio: 'http://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=consulta&maestro=TIPOSERVICIO',
  apiProyecto: 'http://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=consulta&maestro=PROYECTO',
  apiMaquinas: 'http://172.16.59.251:5000/maquinas',
  apiSedes: 'http://172.16.51.102:5000/sedes',
  apiAuxiliares: 'http://172.16.51.102:5000/auxiliares',
  apiUnidadNegocio: 'http://172.16.51.102:5000/unidadnegocio',
  apiTipoMo: 'http://172.16.51.102:5000/monedas',
  apiCostos: 'http://172.16.51.102:5000/centrocostos',
  apiAreas: 'http://172.16.51.102:5000/areas',
  apiMaster: 'http://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=load&maestro=',
  apiGetPeriod : 'http://172.16.51.102:5000/getPeriod',
  postCreatePeriod : 'http://172.16.51.102:5000/postCreatePeriod',
  apiGetPeriodClose : 'http://172.16.51.102:5000/apiGetPeriodClose',
  postClosePeriod : 'http://172.16.51.102:5000/postClosePeriod',
  apiGetPeriodBudget : 'http://172.16.51.102:5000/apiGetPeriodBudget',
  apiPostCreaBudget : 'http://172.16.51.102:5000/apiPostCreaBudget',
  apiGetBudget : 'http://172.16.51.102:5000/apiGetBudget',
  apiGetBudgets : 'http://172.16.51.102:5000/GetBudgets',
  apiGetPeriodFP : 'http://172.16.51.102:5000/apiGetPeriodFP',
  apiGetFPAll : 'http://172.16.51.102:5000/apiGetFPAll',
  apiPostFPByID : 'http://172.16.51.102:5000/apiPostFPByID',
  apiPostCreateFP : 'http://172.16.51.102:5000/apiPostCreateFP',
  apiPostSendApproveFP : 'http://172.16.51.102:5000/apiPostSendApproveFP',
  apiPostRejectFP : 'http://172.16.51.102:5000/apiPostRejectFP',
  apiPostApproveFP : 'http://172.16.51.102:5000/apiPostApproveFP',
  apiPostLoadFloatP : 'http://172.16.51.102:5000/apiPostLoadFloatP',
  apigetDetailFloat : 'http://172.16.51.102:5000/apigetDetailFloat',
  apipostCloseBudget : 'http://172.16.51.102:5000/CloseBudget',
  apiPostPeriodReportFP : 'http://172.16.51.102:5000/apiPostPeriodReportFP',
  apiPostPeriodReportBudget : 'http://172.16.51.102:5000/apiPostPeriodReportBudget',
  apiPostPeriodReportCM1 : 'http://172.16.51.102:5000/apiPostPeriodReportCM1',
  apiPostPeriodReportCM2 : 'http://172.16.51.102:5000/apiPostPeriodReportCM2',
  apiPostPeriodReportCM3 : 'http://172.16.51.102:5000/apiPostPeriodReportCM3',
  apiPostPeriodReportCM4 : 'http://172.16.51.102:5000/apiPostPeriodReportCM4',
  apiPostPeriodReportCM5 : 'http://172.16.51.102:5000/apiPostPeriodReportCM5',
  apiPostPeriodReportCM6 : 'http://172.16.51.102:5000/apiPostPeriodReportCM6',
  apiPostPeriodReportCM7 : 'http://172.16.51.102:5000/apiPostPeriodReportCM7',
  apiPostPeriodReportCM8 : 'http://172.16.51.102:5000/apiPostPeriodReportCM8',
  apiPostPeriodReportCM9 : 'http://172.16.51.102:5000/apiPostPeriodReportCM9',
  apiPostPeriodReportCM10 : 'http://172.16.51.102:5000/apiPostPeriodReportCM10',
  apiPostPeriodReportCCD : 'http://172.16.51.102:5000/apiPostPeriodReeportCCD',
  apiGetPeriodFE : 'http://172.16.51.102:5000/apiGetPeriodFE',
  apiGetFEAll : 'http://172.16.51.102:5000/apiGetFEAll',
  apiPostFEByID : 'http://172.16.51.102:5000/apiPostFEByID',
  apiPostCreateFE : 'http://172.16.51.102:5000/apiPostCreateFE',
  apiPostSendApproveFE : 'http://172.16.51.102:5000/apiPostSendApproveFE',
  apiPostRejectFE : 'http://172.16.51.102:5000/apiPostRejectFE',
  apiPostApproveFE : 'http://172.16.51.102:5000/apiPostApproveFE',
  apiPostLoadFloatE : 'http://172.16.51.102:5000/apiPostLoadFloatE',
  apigetDetailFloatE : 'http://172.16.51.102:5000/apigetDetailFloatE',
  apiPostPeriodReportFE : 'http://172.16.51.102:5000/apiPostPeriodReportFE',
  apiGetPeriodMT : 'http://172.16.51.102:5000/apiGetPeriodMT',
  apiGetMTAll : 'http://172.16.51.102:5000/apiGetMTAll',
  apiPostMTByID : 'http://172.16.51.102:5000/apiPostMTByID',
  apiPostCreateMT : 'http://172.16.51.102:5000/apiPostCreateMT',
  apiPostSendApproveMT : 'http://172.16.51.102:5000/apiPostSendApproveMT',
  apiPostRejectMT : 'http://172.16.51.102:5000/apiPostRejectMT',
  apiPostApproveMT : 'http://172.16.51.102:5000/apiPostApproveMT',
  apiPostLoadMeet : 'http://172.16.51.102:5000/apiPostLoadMeet',
  apigetDetailMeet : 'http://172.16.51.102:5000/apigetDetailMeet',
  apiPostPeriodReportMT : 'http://172.16.51.102:5000/apiPostPeriodReportMT',
  apiGetPeriodPagos : 'http://172.16.51.102:5000/apiGetPeriodPagos',
  apiGetPagosAll : 'http://172.16.51.102:5000/apiGetPagosAll',
  apiPostPagosByID : 'http://172.16.51.102:5000/apiPostPagosByID',
  apiPostCreatePagos : 'http://172.16.51.102:5000/apiPostCreatePagos',
  apiPostSendApprovePagos : 'http://172.16.51.102:5000/apiPostSendApprovePagos',
  apiPostRejectPagos : 'http://172.16.51.102:5000/apiPostRejectPagos',
  apiPostApprovePagos : 'http://172.16.51.102:5000/apiPostApprovePagos',
  apiPostLoadPagos : 'http://172.16.51.102:5000/apiPostLoadPagos',
  apigetDetailPagos : 'http://172.16.51.102:5000/apigetDetailPagos',
  apiPostPeriodReportPagos : 'http://172.16.51.102:5000/apiPostPeriodReportPagos',
  apiGetAdReAll : 'http://172.16.51.102:5000/apiGetAdReAll',
  apiPostAdReByID : 'http://172.16.51.102:5000/apiPostAdReByID',
  apiPostRejectAdRe : 'http://172.16.51.102:5000/apiPostRejectAdRe',
  apiPostApproveAdRe : 'http://172.16.51.102:5000/apiPostApproveAdRe',
  apigetDetailAdRe : 'http://172.16.51.102:5000/apigetDetailAdRe',
  apiPostPeriodReportFe : 'http://172.16.51.102:5000/apiPostPeriodReportFe',
  apiPostPeriodReportAe : 'http://172.16.51.102:5000/apiPostPeriodReportAe',
  apiPostPeriodReportRe: 'http://172.16.51.102:5000/apiPostPeriodReportRe',
  apiPostLoadAdicion : 'http://172.16.51.102:5000/apiPostLoadAdicion',
  apiPostLoadReduccion : 'http://172.16.51.102:5000/apiPostLoadReduccion',
  apiGetRunPagos: 'http://172.16.51.102:5000/apiGetRunPagos',
  apiRollbackbyPeriod: 'http://172.16.51.102:5000/apiRollbackbyPeriod',
  apiPostPeriodRevenue: 'http://172.16.51.102:5000/apiPostPeriodRevenue',
  apiPostLoadRevenue: 'http://172.16.51.102:5000/apiPostLoadRevenue',
  apiGetRevenues : 'http://172.16.51.102:5000/apiGetRevenues',
  apiGetrevenue : 'http://172.16.51.102:5000/apiGetrevenue',
  apipostCloseRevenue : 'http://172.16.51.102:5000/apipostCloseRevenue',
  apiPostCreaDistribution : 'http://172.16.51.102:5000/apiPostCreaDistribution',
  apiGetDistributions : 'http://172.16.51.102:5000/apiGetDistributions',
  apiGetPeriodDistribution: 'http://172.16.51.102:5000/apiGetPeriodDistribution',
  apipostCloseDistribution : 'http://172.16.51.102:5000/apipostCloseDistribution',
  apipostCloseDistributionT : 'http://172.16.51.102:5000/apipostCloseDistributionT',
  apiGetDistribution: 'http://172.16.51.102:5000/apiGetDistribution',
  apiGetListProyectos: 'http://172.16.51.102:5000/apiGetListProyectos'

};
*/

export const CONFIG = {
  apiUrlLogin: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=form,properties,execute,newwindow&_program=%2FAKD+International%2FSTP%2FSTP_GetUserSession',
  apiFlujoCaja: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=consulta&maestro=FLUJOCAJACORPORATIVO',
  apiTipoServicio: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=consulta&maestro=TIPOSERVICIO',
  apiProyecto: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=consulta&maestro=PROYECTO',
  apiMaquinas: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=consulta&maestro=MAQUINAS',
  apiSedes: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=consulta&maestro=SEDE',
  apiAuxiliares: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=consulta&maestro=AUXILIARES',
  apiUnidadNegocio: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=consulta&maestro=UNIDADNEGOCIO',
  apiTipoMo: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=consulta&maestro=TIPOMONEDA',
  apiCostos: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=consulta&maestro=CENTROCOSTO',
  apiAreas: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=consulta&maestro=AREAS',
  apiMaster: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=load&maestro=',
  apiGetPeriod : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=ObtienePeriodosAP',
  postCreatePeriod : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=InsertPeriodo',
  apiGetPeriodClose : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiGetPeriodClose',
  postClosePeriod : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=postClosePeriod',
  apiGetPeriodBudget : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=GetPeriodBudget',
  apiPostCreaBudget : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=CreaBudget',
  apiGetBudget : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=GetBudget',
  apiGetBudgets : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=GetBudgets',
  apipostCloseBudget : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=CloseBudget',
  apiGetPeriodFP : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiGetPeriodFP',
  apiGetFPAll : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiGetFPAll',
  apiPostFPByID : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostFPByID',
  apiPostCreateFP : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostCreateFP',
  apiPostSendApproveFP : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostSendApproveFP',
  apiPostRejectFP : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostRejectFP',
  apiPostApproveFP : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostApproveFP',
  apiPostLoadFloatP : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostLoadFloatP',
  apigetDetailFloat : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apigetDetailFloat',
  deleteAll : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=deleteAll',
  apiPostPeriodReportFP : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=PeriodReportFI',
  apiPostPeriodReportBudget: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FReportBudget&action=PeriodReportBudget',
  apiGetPeriodFE : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiGetPeriodFE',
  apiGetFEAll : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiGetFEAll',
  apiPostFEByID : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostFEByID',
  apiPostCreateFE : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostCreateFE',
  apiPostSendApproveFE : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostSendApproveFE',
  apiPostRejectFE : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostRejectFE',
  apiPostApproveFE : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostApproveFE',
  apiPostLoadFloatE : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostLoadFloatE',
  apigetDetailFloatE : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apigetDetailFloatE',
  apiPostPeriodReportFE : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=PeriodReportFE',
  apiGetPeriodMT : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiGetPeriodMT',
  apiGetMTAll : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiGetMTAll',
  apiPostMTByID : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostMTByID',
  apiPostCreateMT : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostCreateMT',
  apiPostSendApproveMT : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostSendApproveMT',
  apiPostRejectMT : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostRejectMT',
  apiPostApproveMT : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostApproveMT',
  apiPostLoadMeet : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostLoadMeet',
  apigetDetailMeet : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apigetDetailMeet',
  apiPostPeriodReportMT : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=PeriodReportMT',
  apiGetPeriodPagos : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiGetPeriodPagos',
  apiGetPagosAll : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiGetPagosAll',
  apiPostPagosByID : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostPagosByID',
  apiPostCreatePagos : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostCreatePagos',
  apiPostSendApprovePagos : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostSendApprovePagos',
  apiPostRejectPagos : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostRejectPagos',
  apiPostApprovePagos : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostApprovePagos',
  apiPostLoadPagos : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostLoadPagos',
  apigetDetailPagos : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apigetDetailPagos',
  apiPostPeriodReportPagos : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=PeriodReportPagos',
  apiGetAdReAll : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiGetAdReAll',
  apiPostAdReByID : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostAdReByID',
  apiPostRejectAdRe : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostRejectAdRe',
  apiPostApproveAdRe : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostApproveAdRe',
  apigetDetailAdRe : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apigetDetailAdRe',
  apiPostPeriodReportAe : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostPeriodReportAe',
  apiPostPeriodReportRe: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostPeriodReportRe',
  apiPostLoadAdicion : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostLoadAdicion',
  apiPostLoadReduccion : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FAKADMAPI&action=apiPostLoadReduccion',
  apiGetRunPagos: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FValidaPagos&action=LOADMASTER',
  apiRollbackbyPeriod: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FeliminaRegistros',
  apiPostPeriodRevenue: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FRevenueAPI&action=PeriodRevenue',
  apiPostLoadRevenue: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FRevenueAPI&action=LoadRevenue',
  apiGetRevenues : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FRevenueAPI&action=apiGetRevenues',
  apiGetrevenue : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FRevenueAPI&action=apiGetrevenue',
  apipostCloseRevenue : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FRevenueAPI&action=apipostCloseRevenue',
  apiPostPeriodReportCM1 : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FReportCM1&action=apiPostPeriodReportCM1',
  apiPostPeriodReportCM2 : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FReportCM2&action=apiPostPeriodReportCM2',
  apiPostPeriodReportCM3 : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FReportCM3&action=apiPostPeriodReportCM3',
  apiPostPeriodReportCM4 : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FReportCM4&action=apiPostPeriodReportCM4',
  apiPostPeriodReportCM5 : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FReportCM5&action=apiPostPeriodReportCM5',
  apiPostPeriodReportCM6 : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FReportCM6&action=apiPostPeriodReportCM6',
  apiPostPeriodReportCM7 : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FReportCM7&action=apiPostPeriodReportCM7',
  apiPostPeriodReportCM8 : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FReportCM8&action=apiPostPeriodReportCM8',
  apiPostPeriodReportCM9 : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FReportCM9&action=apiPostPeriodReportCM9',
  apiPostPeriodReportCM10 : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FReportCM10&action=apiPostPeriodReportCM10',
  apiPostPeriodReportCCD : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FReportCCD&action=apiPostPeriodReeportCCD',
  apiPostCreaDistribution : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FDistributionAPI&action=apiPostCreaDistribution',
  apiGetDistributions : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FDistributionAPI&action=apiGetDistributions',
  apiGetPeriodDistribution: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FDistributionAPI&action=apiGetPeriodDistribution',
  apipostCloseDistribution : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FDistributionAPI&action=apipostCloseDistribution',
  apipostCloseDistributionT : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FDistributionAPI&action=apipostCloseDistributionT',
  apiGetDistribution: 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FDistributionAPI&action=apiGetDistribution',
  apiGetListProyectos : 'https://sas.akdcloud.com:8343/SASStoredProcess/do?_action=execute&_program=%2FAKD+International%2FAPI%2FListProyect&action=apiGetListProyectos'  
}
